In [1]:
import pandas as pd

In [2]:
one_dict = {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}
two_dict = {"C": ["C0", "C1", "C2"], "D": ["D0", "D1", "D2"]}

one = pd.DataFrame(one_dict)
two = pd.DataFrame(two_dict)

In [3]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [4]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2

In [5]:
# Concatinate according to the "columns" (axis=1):
pd.concat([one,two], axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [6]:
# This is not a good way to do concatinate:
pd.concat([one,two], axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2

In [7]:
# Add two to the below of the one:
two.columns = one.columns
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2

In [9]:
pd.concat([one,two], axis=0)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  C0  D0
1  C1  D1
2  C2  D2

In [10]:
# How to fix the index of last concatination:
my_df = pd.concat([one,two], axis=0)
my_df.index = range(len(my_df))
my_df

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  C0  D0
4  C1  D1
5  C2  D2