In [1]:
import pandas as pd

###### Working with csv file:

In [10]:
# Reading csv file:
df = pd.read_csv("movie_scores.csv")
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [11]:
# Convertinh df to csv:
df.to_csv("new_df.csv")

###### Working with html file:

In [14]:
url = "https://en.wikipedia.org/wiki/World_population"

In [17]:
# This is first way to read csv file from url, that can be blocked by site:
# tables_list = pd.read_html(url)

In [18]:
# Saving the html from the page source of the site is second way:
# This ways give us all the tables in the html in pandas environment as a list:
tables_list = pd.read_html("world_population.htm")

In [19]:
tables_list[0]

,Population (in billions),1,1.1,2,2.1,3,3.1,4,4.1,5,...,6,6.1,7,7.1,8,8.1,9,9.1,10,10.1
0,Year,1804,1804,1927,1927,1960,1960,1974,1974,1987,...,1999,1999,2011,2011,2022,2022,2037,2037,2057,2057
1,Years elapsed,—,—,123,123,33,33,14,14,13,...,12,12,12,12,11,11,15,15,20,20

In [55]:
table_two = tables_list[1]
table_two

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [53]:
# After taking the table from html maybe it needs cleaning in pandas for making it usable.

In [56]:
# Converting df to html:
table_two.to_html("new_html.html")